"""Recipe Fix

Revision ID: 02243faefb82
Revises: 82d32ed3f9b2
Create Date: 2026-06-17 12:18:55.629904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02243faefb82'
down_revision: Union[str, Sequence[str], None] = '82d32ed3f9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('difficulty_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'difficulties', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    op.drop_column('recipes', 'difficulty_id')
    # ### end Alembic commands ###
